version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.1.2
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./DevFun.sln && dotnet publish ./DevFun.sln -c Release -o ./obj/Docker/publish"
