version: '2'

services:
  devfun.web:
    image: devfun.web:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./DevFun.Web:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  devfun.api:
    image: devfun.api:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./DevFun.Api:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

# http://www.localtest.me/
# http://api.localtest.me/api/jokes
# http://api.localtest.me/api/jokes/random

#  proxy:
#    image: proxy
#    ports: ["80:80","443:443"]
#    build:
#      context: ./Proxy
#      dockerfile: Dockerfile
#    labels:
#      - "com.microsoft.visualstudio.targetoperatingsystem=linux"