version: '3.4'

services:
  devfun.api:
    image: ${DOCKER_REGISTRY}devfunapi
    build:
      context: .
      dockerfile: DevFun.Api/Dockerfile

  devfun.web:
    image: ${DOCKER_REGISTRY}devfunweb
    environment:
      - DevFunApi__Url=http://devfun.api/api
    build:
      context: .
      dockerfile: DevFun.Web/Dockerfile

# http://www.localtest.me/
# http://api.localtest.me/api/jokes
# http://api.localtest.me/api/jokes/random

#  proxy:
#    image: proxy
#    ports: ["80:80","443:443"]
#    build:
#      context: ./Proxy
#      dockerfile: Dockerfile
#    labels:
#      - "com.microsoft.visualstudio.targetoperatingsystem=linux"